# GENERATED by stack-forge — DO NOT HAND-EDIT.
# manifest        : manifest.yaml (sha256 ad7c79a3414fdd48)
# catalog channel : vinothtestorg/alicloud-service-catalog@catalog-nonprod (digest 5b6ffa1e412c081b)
# template-matrix : sha256 63ba8aed81c7fbe1
# forge           : vinothtestorg/stack-forge@v1.0.0 (stackforge 1.0.0, templates sha256 ffca0ef80caff846)
component "claims_docs" {
  source  = "app.terraform.io/vinothkaruppusamy/oss-bucket/alicloud"
  version = "~> 1.1"
  inputs = {
    bucket_name    = "claims-docs-${var.env}-${var.account_id}"
    environment    = var.env
    lifecycle_days = 14
    force_destroy  = false
  }
  providers = {
    alicloud = provider.alicloud.this
  }
}

component "claims_cache" {
  source  = "app.terraform.io/vinothkaruppusamy/redis/alicloud"
  version = "~> 1.0"
  inputs = {
    name           = "claims-cache-${var.env}"
    instance_class = "redis.master.small.default"
    engine_version = "7.0"
    vswitch_id     = var.vswitch_id
    zone_id        = var.zone_id
    tags           = var.common_tags
  }
  providers = {
    alicloud = provider.alicloud.this
  }
}
