# GENERATED by stack-forge — DO NOT HAND-EDIT.
# manifest        : manifest.yaml (sha256 ad7c79a3414fdd48)
# catalog channel : vinothtestorg/alicloud-service-catalog@catalog-nonprod (digest dfaff3072c023fac)
# template-matrix : sha256 45cb0b9a1536fe20
# forge           : vinothtestorg/stack-forge@v1.0.0 (stackforge 1.0.0, templates sha256 ffca0ef80caff846)
identity_token "alicloud" {
  audience = ["alicloud.tfc.vinothkaruppusamy"]
}

deployment "dev" {
  inputs = {
    env               = "dev"
    region            = "ap-southeast-1"
    account_id        = "5698578488787527"
    vpc_id            = "vpc-0jl00000000000000poc3"
    vswitch_id        = "vsw-0jl00000000000000dev"
    zone_id           = "ap-southeast-1a"
    role_arn          = "acs:ram::5698578488787527:role/tfc-poc-app-dev"
    oidc_provider_arn = "acs:ram::5698578488787527:oidc-provider/hcp-terraform"
    identity_token    = identity_token.alicloud.jwt
    common_tags = {
      app_id     = "poc3"
      bu         = "gi"
      cost_ctr   = "CC1234"
      data_class = "internal"
      env        = "dev"
      managed_by = "stack-forge"
    }
  }
}

deployment "uat" {
  inputs = {
    env               = "uat"
    region            = "ap-southeast-1"
    account_id        = "5698578488787527"
    vpc_id            = "vpc-0jl00000000000000poc3"
    vswitch_id        = "vsw-0jl00000000000000uat"
    zone_id           = "ap-southeast-1b"
    role_arn          = "acs:ram::5698578488787527:role/tfc-poc-app-dev"
    oidc_provider_arn = "acs:ram::5698578488787527:oidc-provider/hcp-terraform"
    identity_token    = identity_token.alicloud.jwt
    common_tags = {
      app_id     = "poc3"
      bu         = "gi"
      cost_ctr   = "CC1234"
      data_class = "internal"
      env        = "uat"
      managed_by = "stack-forge"
    }
  }
}

# No orchestrate/auto_approve rule is emitted: every deployment stops for a human
# between plan and apply. Auto-approve rules are a deliberate later addition.
