# GENERATED by stack-forge — DO NOT HAND-EDIT.
# manifest        : manifest.yaml (sha256 ad7c79a3414fdd48)
# catalog channel : vinothtestorg/alicloud-service-catalog@catalog-nonprod (digest 5b6ffa1e412c081b)
# template-matrix : sha256 63ba8aed81c7fbe1
# forge           : vinothtestorg/stack-forge@v1.0.0 (stackforge 1.0.0, templates sha256 ffca0ef80caff846)
required_providers {
  alicloud = {
    source  = "aliyun/alicloud"
    version = "~> 1.245"
  }
}

provider "alicloud" "this" {
  config {
    region = var.region
    assume_role_with_oidc {
      oidc_provider_arn = var.oidc_provider_arn
      role_arn          = var.role_arn
      oidc_token        = var.identity_token
      role_session_name = "tfc-stack-${var.env}"
    }
  }
}
