# GENERATED by stack-forge — DO NOT HAND-EDIT.
# manifest        : manifest.yaml (sha256 ad7c79a3414fdd48)
# catalog channel : vinothtestorg/alicloud-service-catalog@catalog-nonprod (digest 1add95f6a04bb734)
# template-matrix : sha256 45cb0b9a1536fe20
# forge           : vinothtestorg/stack-forge@v1.0.0 (stackforge 1.0.0, templates sha256 ffca0ef80caff846)
variable "env" { type = string }
variable "region" { type = string }
variable "account_id" { type = string }
variable "vpc_id" { type = string }
variable "vswitch_id" { type = string }
variable "zone_id" { type = string }
variable "role_arn" { type = string }
variable "oidc_provider_arn" { type = string }
variable "identity_token" {
  type      = string
  ephemeral = true
}
variable "common_tags" { type = map(string) }
